// app/privacy/page.tsx
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Privacy Policy — AI Digest" };

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-paper text-ink">
      <nav className="border-b border-border px-6 h-14 flex items-center max-w-3xl mx-auto">
        <Link href="/" className="text-sm font-semibold">AI Digest</Link>
        <span className="mx-2 text-ink-faint">/</span>
        <span className="text-sm text-ink-muted">Privacy Policy</span>
      </nav>
      <div className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-2xl font-semibold mb-2">Privacy Policy</h1>
        <p className="text-sm text-ink-faint mb-8">Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>

        <div className="prose prose-sm max-w-none text-ink-muted space-y-6">
          <section>
            <h2 className="text-base font-semibold text-ink mb-2">Data we collect</h2>
            <p>We collect your email address, name, and the source URLs you add to your digest. We store article summaries generated by AI on your behalf. We do not sell your data to third parties.</p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-ink mb-2">How we use it</h2>
            <p>Your email is used for authentication and (if enabled) daily digest delivery. Source URLs are fetched daily to populate your digest. Article content is sent to Google Gemini for summarisation and then stored.</p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-ink mb-2">Third-party services</h2>
            <p>We use Neon (database), Stripe (payments), Resend (email), and Google Gemini (AI). Each has its own privacy policy. Your Gemini API key is encrypted at rest (AES-256) if you provide one.</p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-ink mb-2">Data deletion</h2>
            <p>You can delete your account at any time from Settings. All associated data is removed within 30 days.</p>
          </section>
          <section>
            <h2 className="text-base font-semibold text-ink mb-2">Contact</h2>
            <p>Questions? Email us at <a href="mailto:privacy@aigestapp.com" className="text-accent underline underline-offset-2">privacy@aigestapp.com</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
